# Generated by Django 2.1.2 on 2019-01-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('website_url', models.URLField(max_length=100)),
                ('year_of_est', models.IntegerField(max_length=100)),
                ('bussiness_type', models.CharField(max_length=100)),
                ('number_of_emp', models.IntegerField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('street_add', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('facebook_url', models.URLField(max_length=100, unique=True)),
                ('insta_url', models.URLField(max_length=100, unique=True)),
                ('linkdin_url', models.URLField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_emp', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email_emp', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.IntegerField(max_length=100, unique=True)),
                ('linkdin_emp_url', models.URLField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Contact'),
        ),
    ]
